openapi: 3.0.1
info:
  title: سیستم جامع مدیریت پزشکان
  version: 1.0.0

tags:
  - name: "مدیریت کاربران"
    description: "تمام API های مربوط به ثبت‌نام، ورود و فراموشی رمز عبور"

  - name: "پنل کاربران (بیماران)"
    description: "تمام API های مربوط به فعالیت‌های کاربران"

  - name: "پنل پزشکان"
    description: "تمام API های مربوط به فعالیت‌های پزشکان"

components:
  schemas:
    ErrorBody:
      type: object
      properties:
        success:
          type: boolean
          description: نشان می‌دهد که آیا پیام موفقیت آمیز بوده یا خیر. برای خطاها این مقدار همیشه `false` است.
          example: false

        code:
          type: string
          description: کدی برای مشخص کردن نوع خطا است. از آن می‌توان برای بررسی کردن خطاها در کد استفاده کرد.

        message:
          type: string
          description: توضیح مختصری در مورد خطای اتفاق افتاده است.

  responses:
    Error500Response:
      description: |
        سیستم با خطا مواجه شده است.

        این نوع خطا باید به توسعه‌دهنده گزارش شود.

      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorBody'
          examples:
            hello1:
              value:
                success: false
                code: "server_error"
                message: "An unexpected error has occurred."
            hello2:
              value:
                success: false
                code: "man_error"
                message: "An unexpected error has occurred."
