openapi: 3.0.1
info:
  title: سیستم جامع مدیریت پزشکان
  version: 1.0.0

tags:
  - name: "مدیریت کاربران"
    description: "تمام API های مربوط به ثبت‌نام، ورود و فراموشی رمز عبور"

  - name: "پنل کاربران (بیماران)"
    description: "تمام API های مربوط به فعالیت‌های کاربران"

  - name: "پنل پزشکان"
    description: "تمام API های مربوط به فعالیت‌های پزشکان"

paths:
