# Generated by Django 3.1.7 on 2021-03-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=16, verbose_name='Phone'),
        ),
    ]
