# Generated by Django 3.1.7 on 2021-03-26 08:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.CharField(default=uuid.uuid1, max_length=128, primary_key=True, serialize=False, verbose_name='Unique ID')),
                ('username', models.CharField(max_length=64, verbose_name='Username')),
                ('rule', models.CharField(choices=[('DOCTOR', 'Doctor'), ('PATIENT', 'Patient')], max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
