# Generated by Django 3.1.7 on 2021-03-26 10:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='Username')),
                ('id', models.CharField(default='', max_length=128, verbose_name='User ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=64, verbose_name='Last Name')),
                ('phone', models.CharField(default='', max_length=16, verbose_name='Phone')),
                ('favorite_doctors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), default=list, size=None)),
            ],
        ),
    ]
