# Generated by Django 3.1.7 on 2021-03-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='city',
            field=models.CharField(default='', max_length=64, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='expertise',
            field=models.CharField(default='', max_length=64, verbose_name='Expertise'),
        ),
    ]
