# Generated by Django 3.1.7 on 2021-03-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_added']},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone',
            field=models.CharField(default='', max_length=32, verbose_name='Phone'),
        ),
    ]
